### ISSUE TITLE
能不能获得关键词搜索的结果？

### ISSUE THREAD

**Issue by jhsrcmh** [gnemoug/sina_reptile#1]
你好：
      我也是Hiter，也做新浪爬虫。但是其中的一个问题就是关键词搜索没有提供api，我想的办法是使用自动化测试框架selenium(http://docs.seleniumhq.org/), 但是速度很慢。。。你有好的方法么？

**Comment by gnemoug** [comment]
对不起，那个是我大二时候写的东西，好久不搞了，没什么好的建议可以给你！！！
